#ifndef OPENPP_AUTOMATIC_TESTING_COMMANDS_H_
#define OPENPP_AUTOMATIC_TESTING_COMMANDS_H_

enum Command
{
	NO_COMMAND = 0,
    READ_FILE = 1,

    STOP = 0x100,
	SCANNING = 0x200,
	TESTING = 0x400,
	NEW_COMMAND = 0x800,

	START_SCANNING = 0x01 | SCANNING,

	TEST_SUCCESSFUL_TESTS = 0x01 | TESTING,
	TEST_FAILED_TESTS = 0x02 | TESTING,
	TEST_UNTESTED_TESTS = 0x04 | TESTING,
	TEST_ALL = TEST_SUCCESSFUL_TESTS | TEST_FAILED_TESTS | TEST_UNTESTED_TESTS,
	TEST_FOREVER = 0x08 | TESTING,

	N_COMMANDS
};

#endif // ___OPENPP_AUTOMATIC_TESTING_COMMANDS__H___
